### ISSUE TITLE
Event modifying/deleting notifications

### ISSUE THREAD

**Issue by hurtonypeter** [hurtonypeter/zqfa#13]
Notify people who reserved on an event when it is updated or deleted.

**Comment by harlecin** [comment]
Yes, when an event changes or is deleted they should receive a notification saying what changed/that the event was canceled

**Comment by hurtonypeter** [comment]
It is almost completed, email templates are needed

**Comment by harlecin** [comment]
sent you the templates:)

**Comment by hurtonypeter** [comment]
only delete template is missing

**Comment by hurtonypeter** [comment]
This issue was moved to hurtonypeter/alumni-vienna#2
