### ISSUE TITLE
Newsletter for jobs and events

### ISSUE THREAD

**Issue by hurtonypeter** [hurtonypeter/zqfa#14]
Send an email once a week for all members who subscribed to the mailing list for jobs and/or events. The email should contain the jobs and/or events that was created in the current week.

**Comment by harlecin** [comment]
Yes, ideally people only get an update if there are any new jobs added/events. So no new stuff, no mail. If the events/jobs are deleted before the mail is send in the current week, it should not show in the mail

**Comment by hurtonypeter** [comment]
This issue was moved to hurtonypeter/alumni-vienna#1
