### ISSUE TITLE
Job filtering: old posts

### ISSUE THREAD

**Issue by hurtonypeter** [hurtonypeter/zqfa#4]
Job postings older than a month should be 'greyed out'

**Comment by hurtonypeter** [comment]
This is working fine for me. If the job is more than a month old, it disappears from the list. The member who posted the job will see it in a second table as "my expired jobs" and can renew it for another month.

**Comment by harlecin** [comment]
Ideally, old jobs will still be visible for all people, not just the one who posted it. They should just turn grey after a certain time. The idea is that people see that in the past others provided job postings and will there by have an incentive to do so as well:)

**Comment by hurtonypeter** [comment]
This issue was moved to hurtonypeter/alumni-vienna#9
